export type ProjectMedia = {
  src: string;
  type?: "image" | "video";
};

export type Project = {
  slug: string;
  n: string;
  title: string;
  category: string;
  year: string;
  client: string;
  role: string;
  intro: string;
  main: string;
  dominantColor: string;
  media: ProjectMedia[];
};

const makeMedia = (folder: string, files: string[]): ProjectMedia[] =>
  files.map((file) => ({
    src: `/images/${folder}/${file}`,
    type: file.endsWith(".mp4") ? "video" : "image",
  }));

export const projects: Project[] = [
  {
    slug: "project-1",
    n: "01",
    title: "Erene Haven",
    category: "Luxury Identity / Monogram / Art Direction",
    year: "2026",
    client: "Erene Haven",
    role: "Identity, Monogram, Visual System",
    intro:
      "A serene identity system built around a refined monogram, quiet luxury, and a soft material atmosphere.",
    main: "/images/project-1/main.png",
    dominantColor: "#816E56",
    media: makeMedia("project-1", [
      "main.png",
      "second.png",
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.mp4",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
      "11.jpg",
      "12.jpg",
      "13.jpg",
      "14.mp4",
      "15.jpg",
      "16.jpg",
      "17.mp4",
      "18.jpg",
      "19.jpg",
    ]),
  },
  {
    slug: "project-2",
    n: "02",
    title: "Yallahsurf Vibe",
    category: "Surf Campaign / Visual Identity",
    year: "2026",
    client: "Yallahsurf Vibe",
    role: "Identity, Campaign Direction",
    intro:
      "A surf-inspired visual direction shaped around Moroccan texture, coastal rhythm, and a memorable mark.",
    main: "/images/project-2/main.png",
    dominantColor: "#533927",
    media: makeMedia("project-2", [
      "main.png",
      "second.png",
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
      "11.jpg",
      "12.jpg",
      "13.jpg",
      "14.jpg",
      "15.jpg",
      "16.jpg",
    ]),
  },
  {
    slug: "layers-coffe-shop",
    n: "03",
    title: "Layers Coffee Shop",
    category: "Cafe Identity / Packaging / Atmosphere",
    year: "2026",
    client: "Layers Coffee Shop",
    role: "Identity, Packaging, Social Content",
    intro:
      "A warm coffee shop identity shaped through earthy color, packaging moments, and a calm social rhythm.",
    main: "/images/Layers-coffe-shop/1.jpg",
    dominantColor: "#42210D",
    media: makeMedia("Layers-coffe-shop", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
      "11.jpg",
      "12.mp4",
    ]),
  },
  {
    slug: "maghrebwaves",
    n: "04",
    title: "Maghreb Waves",
    category: "Storytelling / Surf Culture / Social Identity",
    year: "2026",
    client: "Maghreb Waves",
    role: "Storytelling, Surf Culture, Social Identity",
    intro:
      "A surf-inspired brand world built around movement, ocean energy, and visual storytelling.",
    main: "/images/Maghrebwaves/1.jpg",
    dominantColor: "#233C50",
    media: makeMedia("Maghrebwaves", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
      "11.jpg",
      "12.jpg",
      "13.jpg",
      "14.jpg",
      "15.jpg",
      "16.jpg",
    ]),
  },
  {
    slug: "orea-coastal-parfum",
    n: "05",
    title: "Orea Coastal Parfum",
    category: "Perfume Concept / Packaging / Art Direction",
    year: "2026",
    client: "Orea",
    role: "Bottle Concept, Packaging, Visual Direction",
    intro:
      "A perfume concept inspired by organic forms, sea texture, and soft luxury.",
    main: "/images/orea-coastal-parfum/1.jpg",
    dominantColor: "#A5A486",
    media: makeMedia("orea-coastal-parfum", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
    ]),
  },
  {
    slug: "plantino",
    n: "06",
    title: "Plantino",
    category: "Social Identity",
    year: "2026",
    client: "Plantino",
    role: "Content System, Visual Direction",
    intro:
      "A clean social identity designed around simple recognition and steady repetition. The project uses compact compositions to build a consistent voice across the whole set.",
    main: "/images/plantino/1.jpg",
    dominantColor: "#E5E3D6",
    media: makeMedia("plantino", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
    ]),
  },
  {
    slug: "samba-surf-shop",
    n: "07",
    title: "Samba Surf Shop",
    category: "Retail Identity",
    year: "2026",
    client: "Samba Surf Shop",
    role: "Identity, Social Posts",
    intro:
      "A surf-shop identity with quick-read visuals and an easy coastal rhythm. The sequence balances practical brand pieces with moments that feel sunlit, active, and local.",
    main: "/images/Samba-surf-shop/1.jpg",
    dominantColor: "#F1F5D6",
    media: makeMedia("Samba-surf-shop", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
    ]),
  },
  {
    slug: "tafoukt-surf-house",
    n: "08",
    title: "Tafoukt Surf House",
    category: "Hospitality Branding",
    year: "2026",
    client: "Tafoukt Surf House",
    role: "Brand, Social Direction",
    intro:
      "A hospitality story shaped around surf culture, light, and a relaxed sense of place. The images build a welcoming rhythm from first impression to final detail.",
    main: "/images/Tafoukt-surf-house/1.jpg",
    dominantColor: "#959F59",
    media: makeMedia("Tafoukt-surf-house", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
    ]),
  },
  {
    slug: "alya",
    n: "09",
    title: "ALYA",
    category: "Social Identity",
    year: "2026",
    client: "ALYA",
    role: "Identity, Social Direction",
    intro:
      "A visual identity built for a social-first rhythm, moving through clear compositions, repeated brand cues, and a warm editorial sense of presence.",
    main: "/images/ALYA/1.jpg",
    dominantColor: "#341711",
    media: makeMedia("ALYA", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
    ]),
  },
  {
    slug: "flexura-yoga-club",
    n: "10",
    title: "Flexura Yoga Club",
    category: "Wellness Branding",
    year: "2026",
    client: "Flexura Yoga Club",
    role: "Brand, Social System",
    intro:
      "A calm wellness identity shaped through posture, softness, and visual repetition. The story gives the brand a grounded rhythm across every frame.",
    main: "/images/Flexura-Yoga-Club/1.jpg",
    dominantColor: "#344629",
    media: makeMedia("Flexura-Yoga-Club", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
    ]),
  },
  {
    slug: "kite-fly-maroc",
    n: "11",
    title: "Kite Fly Maroc",
    category: "Sports Identity",
    year: "2026",
    client: "Kite Fly Maroc",
    role: "Identity, Campaign Direction",
    intro:
      "A coastal sports identity with an active visual pace, built around motion, air, water, and the immediate energy of outdoor adventure.",
    main: "/images/kite-fly-maroc/1.jpg",
    dominantColor: "#001A47",
    media: makeMedia("kite-fly-maroc", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
    ]),
  },
  {
    slug: "luxe-verve",
    n: "12",
    title: "Luxe Verve",
    category: "Luxury Identity",
    year: "2026",
    client: "Luxe Verve",
    role: "Brand, Visual Direction",
    intro:
      "A restrained luxury system where contrast, texture, and spacing carry the story. Each image adds another layer of polish and atmosphere.",
    main: "/images/Luxe-Verve/1.jpg",
    dominantColor: "#5C5C5D",
    media: makeMedia("Luxe-Verve", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
    ]),
  },
  {
    slug: "surfeye",
    n: "13",
    title: "Surfeye",
    category: "Surf Branding",
    year: "2026",
    client: "Surfeye",
    role: "Identity, Motion, Social",
    intro:
      "A surf identity with a bright, direct visual language. The work moves between still frames and motion while keeping a clean coastal voice.",
    main: "/images/surfeye/1.jpg",
    dominantColor: "#E2DFD8",
    media: makeMedia("surfeye", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.mp4",
    ]),
  },
  {
    slug: "surfun",
    n: "14",
    title: "Surfun",
    category: "Surf Campaign",
    year: "2026",
    client: "Surfun",
    role: "Campaign, Social Direction",
    intro:
      "A compact surf campaign with playful energy and a warm visual pulse. The sequence uses a few strong frames to create a memorable brand beat.",
    main: "/images/surfun/1.jpg",
    dominantColor: "#D68C43",
    media: makeMedia("surfun", [
      "1.jpg",
      "2.mp4",
      "3.jpg",
      "4.jpg",
    ]),
  },
  {
    slug: "yacin-pet",
    n: "15",
    title: "Yacin Pet",
    category: "Pet Brand Identity",
    year: "2026",
    client: "Yacin Pet",
    role: "Brand, Social Content",
    intro:
      "A friendly pet brand system with soft clarity and approachable visuals. The page moves through playful, practical, and recognizable brand moments.",
    main: "/images/yacin-pet/1.jpg",
    dominantColor: "#E2E5EC",
    media: makeMedia("yacin-pet", [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
    ]),
  },
];

export const featuredProjects = projects.slice(0, 6);

export const getProject = (slug: string) => projects.find((project) => project.slug === slug);
